export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCESS = 'LOGIN_SUCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';


export const SELECT_SUBJECT = 'SELECT_SUBJECT'
export const CLEAR_SUBJECT = 'CLEAR_SUBJECT'
export const SUBJECT_REQUEST = 'SUBJECT_REQUEST';
export const SUBJECT_SUCCESS = 'SUBJECT_SUCCESS';
export const SUBJECT_FAILURE = 'SUBJECT_FAILURE';


export const SELECT_MATERIAL = 'SELECT_MATERIAL'
export const CLEAR_MATERIAL = 'CLEAR_MATERIAL'

